---
- name: Install pip requirements
  pip: requirements=~/{{rpc_repo_dir}}/requirements.txt

- name: Copy rpc_deploy directory
  command: cp -a ~/{{rpc_repo_dir}}/etc/{{config_prefix}}_deploy /etc/{{config_prefix}}_deploy
           creates=~/rpc_deploy

- name: Set environment_md5 fact for template
  stat: path=/etc/{{config_prefix}}_deploy/{{config_prefix}}_environment.yml
  register: environment_version

- name: install rpc user config file
  template: src=rpc_user_config.j2
            dest=/etc/{{config_prefix}}_deploy/{{config_prefix}}_user_config.yml

- name: Generate passphrases
  command: ~/{{rpc_repo_dir}}/scripts/pw-token-gen.py --file /etc/{{config_prefix}}_deploy/user_secrets.yml

- name: "template target.sh"
  template: src=target.sh.j2
            dest=~/target.sh
            mode=0755

- name: Dump deployment host IP to local file
  delegate_to: localhost
  copy: content={{ ansible_ssh_host }}
        dest=~/target.ip
