- name: install bonding / bridge dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - ifenslave-2.6
    - bridge-utils
    - vlan

- name: load kernel bonding
  modprobe: name=bonding state=present

- name: load 802.1q module
  modprobe: name=8021q state=present

- name: ensure module persistance
  lineinfile: dest=/etc/modules state=present regexp="^{{ item }}" line="{{ item }}"
  with_items:
    - bonding
    - 8021q

- name: ensure /etc/network/interfaces.d exists
  file: path=/etc/network/interfaces.d state=directory owner=root mode=0655

- name: setup interfaces file
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644

- name: retrieve container ip address
  local_action: script cidr.py {{ mgmt_cidr }} {{ ansible_default_ipv4.address }}
  register: container_address

- name: retrieve vxlan ip address
  local_action: script cidr.py {{ vxlan_cidr }} {{ansible_default_ipv4.address }}
  register: vxlan_address

- name: retrieve storage ip address
  local_action: script cidr.py {{ storage_cidr }} {{ansible_default_ipv4.address }}
  register: storage_address

- name: setup interface cfg files
  template: src=interface.j2 dest=/etc/network/interfaces.d/{{ item.name }}.cfg owner=root group=root mode=0644
  with_items: networking

- name: restart networking
  shell: ifdown -a --exclude=lo; ifup -a
  async: 45
  poll: 0

- name: wait for reconnect
  wait_for: delay=10 host={{ inventory_hostname }} port=22
  delegate_to: localhost
