---
- name: Clone RPC repo
  tags: rpc
  git: >
    repo=git@github.com:rcbops/ansible-lxc-rpc.git
    dest=~/ansible-lxc-rpc
    key_file=~/.ssh/id_rsa

- name: Install pip requirements
  tags: rpc
  pip: requirements=~/ansible-lxc-rpc/requirements.txt

- name: Create rpc_deploy directory
  tags: rpc
  file: >
    path=~/rpc_deploy
    state=directory

- name: Render rpc_user_config template
  tags: rpc
  template: >
    src=rpc_user_config.yml
    dest=~/rpc_deploy/rpc_user_config.yml

- name: Copy rpc_environment.yml
  tags: rpc
  command: >
    cp ~/ansible-lxc-rpc/etc/rpc_deploy/rpc_environment.yml ~/rpc_deploy/rpc_environment.yml
    creates=~/rpc_deploy/rpc_environment.yml

- name: Set glance store to file
  tags: rpc
  lineinfile: >
    dest=~/ansible-lxc-rpc/rpc_deployment/vars/user_variables.yml
    regexp="^glance_default_store"
    line="glance_default_store: file"

- name: Copy target.sh to host[0]
  tags: rpc
  copy: >
    src=target.sh
    dest=~/target.sh
    mode=0755

- name: Dump host[0] IP to local file
  tags: rpc
  connection: local
  delegate_to: local
  copy: >
    content={{ansible_ssh_host}}
    dest=~/target.ip
