---
- name: gather all cinder volumes
  shell: lvs | grep cinder | cut -f 3 -d ' '
  register: cinder_vols

- name: cleanup all gathered cinder volumes
  lvol:
    vg: "{{ cinder_storage.backends.lvm.volume_group }}"
    lv: "{{ item }}"
    state: absent
    force: yes
  with_items: cinder_vols.stdout_lines

- name: remove cinder volumes volume group (lvm)
  lvg: 
    vg: "{{ cinder_storage.backends.lvm.volume_group }}"
    state: absent 
    force: yes
  when: cinder_storage.backends.lvm.volume_group is defined

- name: remove cinder volumes volume group (lvm_ssd)
  lvg: 
    vg: "{{ cinder_storage.backends.lvm_ssd.volume_group }}"
    state: absent
    force: yes
  when: cinder_storage.backends.lvm_ssd.volume_group is defined
