---
- name: Provision dev cluster
  hosts: "{{hosts}}"
  gather_facts: True
  roles:
    - dev-lvm
    - dev-packages
    - dev-networking

- name: Provision dev cluster
  hosts: "{{hosts}}[0]"
  gather_facts: True
  roles:
    - dev-setup-rpc
