rpc_repo_dir: rpc_repo
targetBranch: juno
config_prefix: rpc
repo_url: http://rpc-repo.rackspace.com
razor_url: http://10.127.101.82:8080/api
rpc_user_config:
    container_cidr: 172.29.236.0/22
    tunnel_cidr:  172.29.240.0/22
    storage_cidr:  172.29.248.0/22
    repl_cidr: 172.30.248.0/22
    used_ips:
        - "172.29.236.1,172.29.236.15"
        - "172.29.236.83,172.29.236.127"
        - "172.29.240.83,172.29.240.127"
        - "172.29.248.83,172.29.248.127"
    internal_lb_vip_address: 172.29.236.89
    external_lb_vip_address: 172.29.236.89
    tunnel_bridge: br-vxlan
    container_bridge: br-mgmt
    lb_name:
    networking:
        - name: container
          bridge: br-mgmt
          container_bridge: br-mgmt
          container_interface: eth1
          ip_from_q: container
          type: raw
          group_binds:
            - all_containers
            - hosts
        - name: provider
          bridge: br-vlan
          container_interface: eth11
          type: vlan
          range: 2030:2030
          net_name: vlan
          group_binds:
            - neutron_linuxbridge_agent
        - name: tenant
          bridge: br-vxlan
          container_interface: eth10
          ip_from_q: tunnel
          type: vxlan
          range: 1:1000
          net_name: vxlan
          group_binds:
            - neutron_linuxbridge_agent
        - name: storage
          bridge: br-storage
          container_interface: eth2
          ip_from_q: storage
          type: raw
          group_binds:
            - glance_api
            - cinder_api
            - cinder_volume
            - nova_compute
            - swift_proxy
swift_config:
  part_power: 8
  weight: 100
  min_part_hours: 1
  repl_number: 3
  storage_network: 'br-storage' 
  replication_network: 'br-repl'
  drives:
    - name: sdb
  mount_point: /mnt
  account: private_cloud_qe
  container: sat6-lab02
  storage_policies:
    - name: gold
      index: 0
      default: True
    - name: silver
      index: 1
      repl_number: 3
      depreciated: True
cinder_storage:
  backends:
    netapp:
      username: test
      hostname: test
      password: test
    lvm:
      volume_group: vg_storage
networking:
    - name: lo
      type: loopback
    - name: em1
      type: manual
      directives:
        - "bond-master bond0"
        - "bond-primary em1"
    - name: em3
      type: manual
      directives:
        - "bond-master bond0"
    - name: p1p1
      type: manual
      directives:
        - "bond-master bond1"
        - "bond-primary p1p1"
    - name: p1p2
      type: manual
      directives:
        - "bond-master bond2"
        - "bond-primary p1p2"
    - name: p3p1
      type: manual
      directives:
        - "bond-master bond1"
    - name: p3p2
      type: manual
      directives:
        - "bond-master bond2"
    - name: bond0
      type: static
      directives:
        - "bond-slaves none"
        - "bond-mode active-backup"
        - "bond-miimon 100"
        - "bond-downdelay 200"
        - "bond-updelay 200"
        - "address {{ ansible_default_ipv4.address }}"
        - "netmask {{ ansible_default_ipv4.netmask }}"
        - "gateway {{ ansible_default_ipv4.gateway }}"
        - "dns-nameservers 8.8.8.8 8.8.4.4"
        - "dns-search rcb.rackspace.com"
    - name: bond1
      type: manual
      directives:
        - "up ip link set $IFACE up"
        - "down ip link set $IFACE down"
        - "bond-slaves none"
        - "bond-mode active-backup"
        - "bond-miimon 100"
        - "bond-downdelay 250"
        - "bond-updelay 250"
    - name: bond2
      type: manual
      directives:
        - "up ip link set $IFACE up"
        - "down ip link set $IFACE down"
        - "bond-slaves none"
        - "bond-mode active-backup"
        - "bond-miimon 100"
        - "bond-downdelay 250"
        - "bond-updelay 250"
    - name: bond0.2022
      type: manual
      directives:
        - "vlan-raw-device bond0"
    - name: bond1.2023
      type: manual
      directives:
        - "vlan-raw-device bond1"
    - name: bond2.2024
      type: manual
      directives:
        - "vlan-raw-device bond2"
    - name: bond2.2025
      type: manual
      directives:
        - "vlan-raw-device bond2"
    - name: br-mgmt
      type: static
      directives:
        - "bridge_stp off"
        - "bridge_waitport 0"
        - "bridge_fd 0"
        - "bridge-ports bond0.2022"
        - "address 172.29.236.{{member_number}}/22"
        - "dns-nameservers 8.8.8.8 8.8.4.4"
    - name: br-vxlan
      type: static
      directives:
        - "bridge_stp off"
        - "bridge_waitport 0"
        - "bridge_fd 0"
        - "bridge_ports bond1.2023"
        - "address 172.29.240.{{member_number}}/22"
    - name: br-vlan
      type: manual
      directives:
        - "up ip link set $IFACE up"
        - "down ip link set $IFACE down"
        - "bridge_stp off"
        - "bridge_fd 0"
        - "bridge_maxwait 0"
        - "bridge_ports bond1"
    - name: br-storage
      type: static
      directives:
        - "bridge_stp off"
        - "bridge_waitport 0"
        - "bridge_fd 0"
        - "bridge-ports bond2.2024"
        - "address 172.29.248.{{member_number}}/22"
    - name: br-repl
      type: static
      directives:
        - "bridge_stp off"
        - "bridge_waitport 0"
        - "bridge_fd 0"
        - "bridge-ports bond2.2025"
        - "address 172.30.248.{{member_number}}/22"
