---
- name: Delete hosts
  tags: delete-hosts
  hosts: hosts
  gather_facts: false
  roles:
  - {role: cloud-delete-hosts, tags: ['delete-hosts']}

# - name: Delete networks
#   tags: delete-networks
#   hosts: local
#   gather_facts: false
#   roles:
#   - {role: cloud-delete-networks, tags: ['delete-networks']}
