---
- name: Generate hosts
  tags: hosts
  hosts: local
  connection: local
  gather_facts: false
  tasks:
  - name: Generate hosts
    add_host:
      name: "{{host_prefix}}-node{{item}}"
      groups: hosts
      rax_flavor: "{{rax_flavor}}"
      iface:
        tunnel_dev: eth2
        tunnel_ip: 172.20.{{cluster_id}}.{{item}}/24
        tunnel_id: "{{cluster_id}}"
        tunnel_name: vxlan{{cluster_id}}
    with_sequence: count={{host_count}}
