---
- name: Collect all running containers
  command: lxc-ls
  register: running_containers

- name: Stop local containers
  command: lxc-stop -k -n {{ item }}
  with_items: active_local_containers.stdout_lines

- name: Destroy local containers
  command: lxc-destroy -f -n {{ item }}
  with_items: active_local_containers.stdout_lines

- name: Remove all containers from /etc/hosts
  lineinfile: dest=/etc/hosts regexp="container" state=absent

- name: Recursive delete of /openstack directory
  shell: rm -rf /openstack/*
