---
- name: Collect all running containers
  command: lxc-ls
  register: running_containers

- name: Stop all running containers
  command: lxc-stop -k -n {{ item }}
  with_items: running_containers.stdout_lines

- name: Destroy all running containers
  command: lxc-destroy -f -n {{ item }}
  with_items: running_containers.stdout_lines

- name: Remove all containers from /etc/hosts
  lineinfile: dest=/etc/hosts regexp="{{ item }}" state=absent
  with_items: running_containers.stdout_lines

- name: Recursive delete of /openstack directory
  command: rm -rf /openstack/*
