---
- name: Updating packages
  tags: packages
  apt:
    update_cache: yes
    cache_valid_time: 600
    upgrade: dist
  register: pkgs
  until: pkgs|success

- name: Install packages
  tags: packages
  apt:
    pkg: {{ item }}
    state: present
    update_cache: yes
    cache_valid_time: 600
  register: pkgs
  until: pkgs|success
  with_items: packages
