---
- name: Install pip requirements
  pip: requirements={{ osad_repo_dir }}/requirements.txt

- name: Remove old OSAD user configuration files
  shell: rm -rf /etc/{{ config_prefix }}_deploy/user_*

- name: Copy OSAD user configuration files
  shell: cp --recursive {{ osad_repo_dir }}/etc/{{ config_prefix }}_deploy/user_* /etc/{{ config_prefix }}_deploy

- name: Gather environment MD5
  stat: path=/etc/{{ config_prefix }}_deploy/{{ config_prefix }}_environment.yml
  register: environment_version

- name: Install user configuration file
  template: src=user_config.j2
            dest=/etc/{{ config_prefix }}_deploy/{{ config_prefix }}_user_config.yml

- name: Install user variables file
  template: src=user_variables.j2
            dest=/etc/{{ config_prefix }}_deploy/user_variables.yml

- name: Create passphrases file
  file: path=/etc/{{ config_prefix }}_deploy/user_secrets.yml
        state=touch
        owner=root
        mode=0644

- name: Generate passphrases
  command: "{{ osad_repo_dir }}/scripts/pw-token-gen.py --file /etc/{{ config_prefix }}_deploy/user_secrets.yml"
