---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install packages that are for all hosts
  apt: pkg={{ item }} state=present
  with_items: all
  tags:
    - deployment
    - target

- name: install packages that are for deployment hosts
  apt: pkg={{ item }} state=present
  with_items: deployment
  tags: deployment

- name: install packages that are for target hosts
  apt: pkg={{ item }} state=present
  with_items: target
  tags: target

- name: unblacklist required kernel modules
  lineinfile: dest=/etc/modprobe.d/blacklist.local.conf state=absent line={{ item }}
  with_items:
    - "blacklist e1000e"
    - "blacklist ixgbe"

- name: load {{ item }} module
  modprobe: name={{ item }} state=present
  with_items:
    - e1000e
    - ixgbe

- name: ensure module persistance
  lineinfile: dest=/etc/modules state=present regexp="^{{ item }}" line="{{ item }}"
  with_items:
    - e1000e
    - ixgbe
