---
- name: Ensure xfsprogs package is installed
  apt:
    pkg: "xfsprogs"
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Create LVs for Swift
  lvol:
    vg: "{{ swift_config.vg }}"
    lv: "{{ item.name }}"
    size: "{{ swift_config.lv_size }}"
  with_items: swift_config.drives

- name: Create swift mount dirs
  file:
    state: directory
    path: "{{ swift_config.mount_point }}/{{ item.name }}"
  with_items: swift_config.drives

- name: mkfs.xfs swift partitions
  shell: "xfs_info /dev/{{ swift_config.vg }}/{{ item.name }} || mkfs.xfs -f /dev/{{ swift_config.vg }}/{{ item.name }}"
  with_items: swift_config.drives

- name: Mount swift partitions
  mount: 
    state: mounted
    fstype: xfs
    src: "/dev/{{ swift_config.vg }}/{{ item.name }}"
    name: "{{ swift_config.mount_point }}/{{ item.name }}"
  with_items: swift_config.drives

