---
- name: Down interfaces
  command: ifdown {{item.iface}}
  when: item.iface in ansible_interfaces
  with_items: ifaces

- name: Flush interfaces
  command: ip addr flush {{item.iface}}
  when: item.iface in ansible_interfaces
  with_items: ifaces

- name: Up interfaces
  command: ifup {{item.iface}}
  when: item.iface in ansible_interfaces
  with_items: ifaces

# - name: Ping addresses
#   command: ping -c 1 -q {{item.ipv4}}
#   register: output
#   when: "item.iface in ansible_interfaces and item.ipv4 is defined"
#   with_items:
#   - hostvars
#   - ifaces
#   changed_when: False # Never changed
#   failed_when: output.rc != 0
