---
- name: Rekick cluster nodes
  gather_facts: False
  hosts: all
<<<<<<< HEAD
  tasks:
    - name: Rekick and wait for nodes to become available
      delegate_to: localhost
      rekick:
        host_ip: "{{ ansible_ssh_host }}"
        host_name: "{{ inventory_hostname }}"
        kick_wait: 2400
        kick_tries: 2
        djeep_url: "http://10.127.52.2:8000/api"
=======
  roles:
    - djeep-rekick
>>>>>>> master
