---

## --------- [ Prepare Cluster ] ---------------

- hosts: all
  user: root
  vars_files:
    - vars/packages.yml
  roles:
    - packages
  tags: prepare

- hosts: all
  user: root
  vars_files:
    - vars/pip.yml
  roles:
    - pip
  tags: prepare

- hosts: all
  user: root
  roles:
    - role: networking
      bring_up_interfaces: yes
  tags: prepare

- hosts: all
  tasks:
    - name: Create cinder volumes vg
      lvg:
        vg: "{{item.name}}"
        pvs: "{{item.device}}"
      with_items: vgs
  tags: prepare

- hosts: all
  tags: prepare
  user: root
  roles:
    - configure-rpc-swift-lvs
    - setup-git

- hosts: infrastructure[0]
  tags: prepare
  user: root
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: bootstrap-ansible

- hosts: all
  tags: prepare
  user: root
  roles:
    - configure-rpc-compute
    - configure-rpc-swift

## --------- [ Run os-ansible-deployment ] ---------------
- hosts: infrastructure[0]
  tags: run
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: run-playbooks
      script_env:
        DEPLOY_TEMPEST: "yes"

## --------- [ Retrieve tempest report ] ---------------

# The results file cannot be retrieved directly from the utility container as
# the jenkins-rpc inventory does not include containers.
# osad/scripts/run-tempest.sh copies tempest_results from the utility container
# to /tmp on the host.  This play copies tempest_results from the deployment
# host to the jenkins workspace.
- hosts: infrastructure
  tags: get_tempest_report
  tasks:
    - name: Get tempest results report
      fetch:
        src: /tmp/tempest_results.xml
        dest: results/
        flat: yes
        fail_on_missing: no

## --------- [ Clean up nodes] ---------------
- hosts: all
  gather_facts: false
  tags: clean
  roles:
    - djeep-rekick
